apiVersion: v1
kind: Namespace
metadata:
  name: dn-web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: dn-web
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: httpd:2.4
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: dn-web
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
