apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cueweb-app
  namespace: flux-system
spec:
  suspend: false 
  interval: 1m
  path: ./apps/cueweb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dn-cueweb
  timeout: 1m
