apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  suspend: true
  interval: 5m
  path: ./apps/postgresql
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 1m
  # The targetNamespace is set to the namespace where the PostgreSQL resources will be deployed.
  # This is typically the namespace where your database applications will run.
  
  targetNamespace: dn-postgresql
