apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  suspend: true  # Set to true to pause the reconciliation of this Kustomization
  interval: 1m
  path: ./apps/postgresql   # Path to manifests/HelmRelease in your repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dn-postgresql

