apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  force: true
  suspend: false  # Set to true to pause the reconciliation of this HelmRepository
  interval: 30m
  url: https://charts.bitnami.com/bitnami
